#!/bin/bash

echo "🔍 RAILWAY DEPLOYMENT DEBUG"
echo "=========================="

echo -e "\n1. 🏥 HEALTH CHECK ISSUES"
echo "========================"
echo "Railway health check failing at /health endpoint"
echo "Possible causes:"
echo "- Server not binding to 0.0.0.0:PORT"
echo "- Health endpoint throwing errors"
echo "- Supabase connection timeout"
echo "- Environment variables missing"
echo ""

echo -e "\n2. 🔧 FIXES APPLIED"
echo "=================="
echo "✅ Added timeout to Supabase health check (5s)"
echo "✅ Made health endpoint always return 200 status"
echo "✅ Added graceful shutdown handling"
echo "✅ Improved error logging"
echo "✅ Fixed server binding to 0.0.0.0"
echo ""

echo -e "\n3. 🌐 ENVIRONMENT VARIABLES TO CHECK"
echo "==================================="
echo "Required for Railway:"
echo "- PORT (auto-set by Railway)"
echo "- SUPABASE_URL"
echo "- SUPABASE_SERVICE_KEY"
echo "- WHATSAPP_TOKEN"
echo "- WHATSAPP_PHONE_ID"
echo "- WEBHOOK_VERIFY_TOKEN"
echo ""

echo -e "\n4. 📋 RAILWAY DEPLOYMENT CHECKLIST"
echo "=================================="
echo "1. Check Railway environment variables match production values"
echo "2. Verify Supabase URL is correct (not pooler URL)"
echo "3. Test health endpoint locally: npm start && curl http://localhost:3000/health"
echo "4. Check Railway logs for startup errors"
echo "5. Verify no blocking middleware on /health route"
echo ""

echo -e "\n5. 🚀 NEXT DEPLOYMENT"
echo "===================="
echo "The fixes should resolve:"
echo "- Health check timeouts"
echo "- Server startup issues"
echo "- Environment detection"
echo "- Graceful shutdown"
echo ""

echo "✅ Ready for Railway redeployment"